version: "3.9"
services:
  auth-service:
    build:
      context: ./phase-1/server/auth-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75
    restart: unless-stopped
  client:
    build:
      context: ./phase-1/client
    ports:
      - "5173:80"
    depends_on:
      - auth-service
    restart: unless-stopped


